FROM puckel/docker-airflow:1.10.9
RUN pip install requests
RUN pip install pandas
RUN pip install google.cloud
RUN pip install --upgrade 'google-cloud-bigquery[bqstorage,pandas]'
RUN pip install pandas_gbq
